What Beethoven’s pieces did they mention in the movie? (3) 


Who did Beethoven want to study with? Did he ever get a chance to study with him? (2)  
How old was Beethoven when he moved to Vienna? (1) 
What were 1793 pianos like? Was Beethoven satisfied with them? (2) 
What did general public think of Beethoven’s music? Who supported Beethoven financially? (2)  
When did he notice that his hearing is getting worse? (1) 
What is Heiligenstadt Testament? (1) 
What did the Symphony No. 5 become a symbol of? How does the symphony start and end (key)? (2) 
How long was the concert where they performed Beethoven’s fifth symphony? (1) 
Who was Beethoven’s Immortal Beloved? (1) 
What was the title of Beethoven’s opera? (1) 
How did he communicate with the society during the last nine years of his life, while he was already deaf? (1) 
What is special about Beethoven’s last symphony (no. 9)? (1) 
Who was Carl? Beethoven had a complicated relationship with him. (1)  
How old was Beethoven when he died? How many people attended his funeral? (2)